//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4601
        ///1583
        ///2995
        ///5319
        ///3352
        ///1722
        ///4331
        ///5840
        ///3339
        ///5341
        ///3415
        ///1297
        ///1610
        ///2703
        ///
        ///5928
        ///1266
        ///6405
        ///4354
        ///2815
        ///1621
        ///3545
        ///1733
        ///2162
        ///1155
        ///3674
        ///4055
        ///4262
        ///2115
        ///
        ///25873
        ///16103
        ///17042
        ///
        ///6479
        ///1521
        ///6902
        ///6331
        ///6146
        ///1591
        ///2063
        ///2149
        ///1463
        ///1865
        ///2598
        ///6893
        ///3617
        ///
        ///1431
        ///8935
        ///8134
        ///8885
        ///8698
        ///8884
        ///7982
        ///3617
        ///7079
        ///
        ///34031
        ///8383
        ///
        ///3697
        ///1199
        ///3703
        ///1322
        ///5679
        ///1627
        ///5910
        ///1092
        ///6445
        ///2371
        ///3672
        ///2281
        ///2710
        ///5111
        ///
        ///17480
        ///
        ///58355
        ///
        ///3711
        ///2406
        ///2101
        ///1406
        ///5376
        ///2149
        ///4608
        ///6768
        ///6322
        ///3792
        ///42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Elves {
            get {
                return ResourceManager.GetString("Day01Elves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Z
        ///C Z
        ///A X
        ///A X
        ///B Z
        ///B Z
        ///B Z
        ///A Z
        ///B X
        ///A X
        ///A X
        ///A X
        ///C Z
        ///C Z
        ///C X
        ///A X
        ///A X
        ///A X
        ///C Z
        ///B Z
        ///C Z
        ///A Y
        ///B Z
        ///A X
        ///C Y
        ///A X
        ///A X
        ///C Y
        ///C Z
        ///A Y
        ///B Z
        ///A X
        ///C Y
        ///B Z
        ///B Z
        ///B Z
        ///A X
        ///C X
        ///C X
        ///B Z
        ///A X
        ///C Z
        ///A X
        ///B Z
        ///A Y
        ///C X
        ///A X
        ///C Z
        ///C Z
        ///B Z
        ///C Y
        ///C X
        ///C X
        ///C X
        ///C X
        ///A Y
        ///C Y
        ///C Z
        ///C Y
        ///A X
        ///C Y
        ///A X
        ///B Z
        ///A Y
        ///C X
        ///A X
        ///B Y
        ///A X
        ///C X
        ///C X
        ///C Z
        ///A X
        ///C X
        ///A X
        ///C X
        ///B Z
        ///A Z
        ///B Y
        ///B Z
        ///B Z
        ///A X
        ///C Y
        ///B X
        ///A X
        ///A X
        ///B Z
        ///A X
        ///C X
        ///C Z
        ///C Z
        ///A X
        ///C Z
        ///C Z
        ///C Z
        ///C X
        ///C Z
        ///A X
        ///B Z
        ///B Y
        ///C Z
        ///B Z
        ///B Z
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Rock {
            get {
                return ResourceManager.GetString("Day02Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gfWpjRRQffQGCHHJsGqjsj
        ///SclzJZZvmmnPbJtVSqqNBqVCBdSCsd
        ///tlbvZJDZtmtPcJmlPnhMFQWWpMRFTfLDRRTWRp
        ///HjMPgSWjVrjgbHRRSSMRgjRdpdbGdlcdCvQfcCdlwQJfdf
        ///LNDnhtNtLNFFZDtFnhzvdldDflvvDCdlJfldpJ
        ///ZFLFZZmFtFtTNTSPRrVPWWMpRP
        ///qLBSBLRwmgzqCbzCffDlrfCV
        ///TFFFHNWFMFFMpHpGHMTHGNhrldWZCsdZsslZlZfrflDVss
        ///PTMcPGntTThHhTGctnMvSwjjvmmqLBmnjqqgCR
        ///nClJtMwwntqVVPJcgZqq
        ///mjpsDcrcSSFFPZqFBWWgVP
        ///vQcjsvhrvvrmhbmNHMNnlHbNMtCtNM
        ///bgvvhnTQtjrrrhsDDf
        ///pLSMltLzLLSjFrSSjrSJHD
        ///zNWRLBdZPllPQtCvttgCqb
        ///DRlDrrFTNDNlgzsGTBfcnqhhcnJfcrCSqc
        ///MMmm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Rucksack {
            get {
                return ResourceManager.GetString("Day03Rucksack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22-77,14-96
        ///7-99,65-98
        ///22-36,37-62
        ///25-94,24-67
        ///6-91,1-6
        ///88-88,2-88
        ///27-89,58-96
        ///21-82,9-94
        ///38-79,27-80
        ///4-90,30-55
        ///84-97,52-93
        ///12-59,11-12
        ///4-14,5-12
        ///50-84,49-89
        ///3-98,1-3
        ///91-95,8-22
        ///15-66,17-67
        ///27-27,27-90
        ///36-37,37-96
        ///31-32,32-80
        ///1-79,2-78
        ///36-85,20-36
        ///2-2,2-98
        ///33-81,80-99
        ///4-73,45-72
        ///3-89,1-4
        ///6-92,21-91
        ///7-93,2-92
        ///47-89,47-50
        ///64-84,63-65
        ///22-85,21-91
        ///16-31,11-14
        ///4-93,3-93
        ///15-61,61-62
        ///21-23,22-88
        ///59-59,11-58
        ///23-23,22-89
        ///19-87,78-86
        ///13-82,19-83
        ///22-88,76-92
        ///46-47,46-46
        ///30-31, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Assignment {
            get {
                return ResourceManager.GetString("Day04Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             [M] [S] [S]            
        ///        [M] [N] [L] [T] [Q]        
        ///[G]     [P] [C] [F] [G] [T]        
        ///[B]     [J] [D] [P] [V] [F] [F]    
        ///[D]     [D] [G] [C] [Z] [H] [B] [G]
        ///[C] [G] [Q] [L] [N] [D] [M] [D] [Q]
        ///[P] [V] [S] [S] [B] [B] [Z] [M] [C]
        ///[R] [H] [N] [P] [J] [Q] [B] [C] [F]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 1 from 7 to 4
        ///move 3 from 4 to 7
        ///move 4 from 3 to 4
        ///move 5 from 6 to 9
        ///move 1 from 8 to 1
        ///move 2 from 3 to 2
        ///move 3 from 4 to 6
        ///move 1 from 3 to 6
        ///move 9 from 7 to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05Crates {
            get {
                return ResourceManager.GetString("Day05Crates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zdrrgvvntvtzzssgcgqqbvqqzmqmrrprjjpmpwpvpqpwppfqqnvvjbjcbbrnnvwnvnqnncvvqnvqvmmdzdrzzjmmfzmztzczzjpjllgzgnzgznzpzhhvppmjjtbjbjgbjjpfphfhthpprbbzzhbzzvjjsttjwtjwjllzplzlhlqlfqfvflfvlvqvqsshccgffvzzqllpjllcqcpqcpqccbgcccvwvlldclcppcggjhhtbhbrbwbllldndhnnmnmcccvfvtftrfttlhttgltlflgflfrrftrtrgrmggbccnvccvssbmsmnsmszmmsbshbhpbhhtccnmngmnnntznttwnnmffdccrhrshhzhszslzlqqqsqhhrrvmrrhrmhrrdppshpssjhhhtzhzpzzzbrrqqhhtltgltgghlhpphmmbllczcgcrgcrcmmdjdvdssdbsshqqrprhrfrqrlldggpglplqlgqqvfqqwhqqclcwwbrbwbzzmcczqqpzpzhpz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06Tuning {
            get {
                return ResourceManager.GetString("Day06Tuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir jmtrrrp
        ///dir jssnn
        ///dir lbrmb
        ///11968 pcccp
        ///$ cd jmtrrrp
        ///$ ls
        ///77968 chq.jvb
        ///dir fmgsql
        ///$ cd fmgsql
        ///$ ls
        ///dir dbnsfp
        ///dir vvp
        ///$ cd dbnsfp
        ///$ ls
        ///51021 crlq.lrj
        ///186829 dhcrzvbr.wmn
        ///16232 fvhn.fqm
        ///54150 qpbqqj.rpg
        ///$ cd ..
        ///$ cd vvp
        ///$ ls
        ///179105 rrcsndz.tzp
        ///$ cd ..
        ///$ cd ..
        ///$ cd ..
        ///$ cd jssnn
        ///$ ls
        ///dir bphfqs
        ///dir dbnsfp
        ///dir pcccp
        ///dir snr
        ///dir zjbvwsnv
        ///$ cd bphfqs
        ///$ ls
        ///110077 dhcrzvbr.wmn
        ///$ cd ..
        ///$ cd dbnsfp
        ///$ ls
        ///dir hgvh
        ///dir jtqdcmsz
        ///154197 rrcsndz.tzp
        ///$ cd hgvh
        ///$  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07Terminal {
            get {
                return ResourceManager.GetString("Day07Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 202002313322443443333413205214140320025450316364504141264123114304203303114001123204003420102030300
        ///212313000221124342025540453251212255520310035503014622512241404324240404402541331004400300331322110
        ///332010030224230340301531501004040246520352260460326354116252046344244524210334140401240030314221201
        ///221301221024131121450340303252214260131364111213343344405130626304123155314054543541311324344211033
        ///001134433000214135052445324455546624654355260523323125133253553045204251430400315121003433044422220
        ///1100243 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08Trees {
            get {
                return ResourceManager.GetString("Day08Trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D 2
        ///U 1
        ///D 1
        ///U 2
        ///D 2
        ///U 2
        ///R 2
        ///D 1
        ///L 1
        ///U 2
        ///D 1
        ///R 1
        ///U 1
        ///D 1
        ///U 1
        ///D 2
        ///L 1
        ///D 1
        ///U 1
        ///R 1
        ///D 1
        ///R 1
        ///L 2
        ///D 1
        ///R 2
        ///U 2
        ///L 1
        ///U 1
        ///R 1
        ///D 1
        ///U 2
        ///D 1
        ///U 1
        ///R 1
        ///L 1
        ///U 1
        ///R 1
        ///D 2
        ///U 2
        ///R 2
        ///L 1
        ///R 2
        ///L 2
        ///D 1
        ///L 2
        ///R 2
        ///D 2
        ///R 2
        ///D 1
        ///R 2
        ///D 1
        ///R 1
        ///U 2
        ///L 2
        ///D 1
        ///R 2
        ///U 2
        ///L 1
        ///U 1
        ///R 2
        ///D 2
        ///L 1
        ///U 2
        ///R 2
        ///U 1
        ///R 1
        ///D 2
        ///L 1
        ///R 2
        ///U 1
        ///D 2
        ///U 1
        ///R 1
        ///L 2
        ///D 1
        ///U 1
        ///L 1
        ///R 2
        ///L 2
        ///R 1
        ///D 2
        ///L 1
        ///R 2
        ///L 2
        ///R 2
        ///U 2
        ///L 2
        ///R 2
        ///L 2
        ///R 1
        ///L 2
        ///D 1
        ///L 2
        ///D 1
        ///R 2
        ///D 2
        ///U 2
        ///L 2
        ///R 2
        ///U 2
        ///D 1
        ///R 2
        ///L  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09Rope {
            get {
                return ResourceManager.GetString("Day09Rope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noop
        ///noop
        ///addx 5
        ///addx 1
        ///addx 10
        ///addx -4
        ///noop
        ///addx -1
        ///noop
        ///addx 5
        ///addx -5
        ///addx 9
        ///addx 2
        ///addx -15
        ///addx 18
        ///addx 8
        ///addx -2
        ///noop
        ///addx -18
        ///addx 21
        ///addx 1
        ///addx -37
        ///addx 27
        ///addx -24
        ///addx 2
        ///addx 5
        ///addx -7
        ///addx 26
        ///addx -16
        ///addx 2
        ///addx 5
        ///addx -15
        ///noop
        ///addx 20
        ///addx 2
        ///addx 4
        ///addx -3
        ///addx 2
        ///noop
        ///addx 3
        ///addx 2
        ///addx 5
        ///addx -40
        ///addx 2
        ///addx 33
        ///addx -30
        ///addx 5
        ///addx 5
        ///addx 17
        ///addx -19
        ///addx 2
        ///addx 5
        ///addx 20
        ///addx -16
        ///addx 3
        ///addx -2
        ///addx 7
        ///noop
        ///addx -2
        ///addx 5
        ///addx 2
        ///add [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10Cathode {
            get {
                return ResourceManager.GetString("Day10Cathode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkey 0:
        ///  Starting items: 98, 70, 75, 80, 84, 89, 55, 98
        ///  Operation: new = old * 2
        ///  Test: divisible by 11
        ///    If true: throw to monkey 1
        ///    If false: throw to monkey 4
        ///
        ///Monkey 1:
        ///  Starting items: 59
        ///  Operation: new = old * old
        ///  Test: divisible by 19
        ///    If true: throw to monkey 7
        ///    If false: throw to monkey 3
        ///
        ///Monkey 2:
        ///  Starting items: 77, 95, 54, 65, 89
        ///  Operation: new = old + 6
        ///  Test: divisible by 7
        ///    If true: throw to monkey 0
        ///    If false: throw to monkey 5
        ///
        ///Monkey 3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11Monkey {
            get {
                return ResourceManager.GetString("Day11Monkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abaaaaaccccccccccccccccccaaaaaaaaaaaaaccccaaaaaaaccccccccccccccccccccccccccccaaaaaa
        ///abaaaaaaccaaaacccccccccccaaaaaaaaacaaaacaaaaaaaaaacccccccccccccccccccccccccccaaaaaa
        ///abaaaaaacaaaaaccccccccccaaaaaaaaaaaaaaacaaaaaaaaaacccccccccccccaacccccccccccccaaaaa
        ///abaaaaaacaaaaaacccccccccaaaaaaaaaaaaaaccaaacaaaccccccccccccccccaacccccccccccccccaaa
        ///abccaaaccaaaaaacccaaaaccaaaaaaaaaaaaaccccaacaaacccccccccaacaccccacccccccccccccccaaa
        ///abcccccccaaaaaccccaaaacccccaaaaacccaaaccaaaaaaccccccccccaaaaccccccccccccccccccccaac
        ///ab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day12Heightmap {
            get {
                return ResourceManager.GetString("Day12Heightmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[[2],3,[],[]]]
        ///[[6,9,1,3,[[2,9],4,8,[9,2,1]]],[],[[3],3]]
        ///
        ///[[7,[10,[3,2,6],10,[10],[4,8,7,4,7]]],[9,8,8,7]]
        ///[[3,9],[2,2,[6,[1,8],[10,7,8]],[[1,9,8],[],[],[2,4,2],[3]]],[8,[],[[7]]]]
        ///
        ///[[2,[6,1,0]],[],[]]
        ///[[[9],[[1,4],[1,10,9,2,6],6,2],4,[[10,9,3,8],6]],[[10,[]],[[1,8],6,6,7,0],[[1,9],0,4,[3],[8,8,8,10]]],[],[8,6,3,[5]],[[10],[[6,4,2,0],6,1,8,0],0,[[9],[3,4,0,5],[10]]]]
        ///
        ///[[2,7],[1,[4,[9,9,6]],0]]
        ///[[[[5,2]],10,5]]
        ///
        ///[[4,2,[2,[6]],5],[],[[[8],[6,10]],4,5,[[10,0],[10,1,9,10]]]]
        ///[[[[3,10,2,9,10],8,[4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day13Distress {
            get {
                return ResourceManager.GetString("Day13Distress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500,30 -&gt; 504,30
        ///503,28 -&gt; 507,28
        ///477,136 -&gt; 477,133 -&gt; 477,136 -&gt; 479,136 -&gt; 479,135 -&gt; 479,136 -&gt; 481,136 -&gt; 481,127 -&gt; 481,136 -&gt; 483,136 -&gt; 483,131 -&gt; 483,136 -&gt; 485,136 -&gt; 485,129 -&gt; 485,136 -&gt; 487,136 -&gt; 487,135 -&gt; 487,136
        ///496,97 -&gt; 496,99 -&gt; 488,99 -&gt; 488,103 -&gt; 508,103 -&gt; 508,99 -&gt; 502,99 -&gt; 502,97
        ///537,66 -&gt; 541,66
        ///491,23 -&gt; 491,15 -&gt; 491,23 -&gt; 493,23 -&gt; 493,18 -&gt; 493,23 -&gt; 495,23 -&gt; 495,15 -&gt; 495,23 -&gt; 497,23 -&gt; 497,15 -&gt; 497,23 -&gt; 499,23 -&gt; 499,18 -&gt; 499,23 -&gt; 501,23 -&gt; 501,14 -&gt; 501,23 -&gt; 50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day14Regolith {
            get {
                return ResourceManager.GetString("Day14Regolith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor at x=98246, y=1908027: closest beacon is at x=1076513, y=2000000
        ///Sensor at x=1339369, y=2083853: closest beacon is at x=1076513, y=2000000
        ///Sensor at x=679177, y=3007305: closest beacon is at x=1076513, y=2000000
        ///Sensor at x=20262, y=3978297: closest beacon is at x=13166, y=4136840
        ///Sensor at x=3260165, y=2268955: closest beacon is at x=4044141, y=2290104
        ///Sensor at x=2577675, y=3062584: closest beacon is at x=2141091, y=2828176
        ///Sensor at x=3683313, y=2729137: closest beacon is at x=4044141, y=229 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day15Beacons {
            get {
                return ResourceManager.GetString("Day15Beacons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve OK has flow rate=0; tunnels lead to valves RW, FX
        ///Valve JY has flow rate=13; tunnel leads to valve TT
        ///Valve FX has flow rate=16; tunnels lead to valves OK, LF, GO, IV
        ///Valve TD has flow rate=0; tunnels lead to valves XZ, ED
        ///Valve VF has flow rate=9; tunnels lead to valves DS, LU, TR, WO
        ///Valve TT has flow rate=0; tunnels lead to valves XZ, JY
        ///Valve KR has flow rate=8; tunnels lead to valves VL, CI, GO, JJ, TQ
        ///Valve HN has flow rate=0; tunnels lead to valves YG, AA
        ///Valve MC has flow rate=24; tunn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16Volcanium {
            get {
                return ResourceManager.GetString("Day16Volcanium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&lt;&lt;&lt;&lt;&gt;&gt;&gt;&lt;&gt;&gt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&lt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&lt;&lt;&gt;&gt;&lt;&lt;&lt;&lt;&gt;&lt;&lt;&gt;&gt;&lt;&lt;&lt;&gt;&lt;&lt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&lt;&lt;&gt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&gt;&lt;&lt;&lt;&gt;&gt;&lt;&lt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&gt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&lt;&lt;&gt;&lt;&lt;&gt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&lt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&lt;&lt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&lt;&lt;&gt;&lt;&lt;&gt;&gt;&gt;&gt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&gt;&gt;&lt;&lt;&lt;&gt;&lt;&lt;&gt;&....
        /// </summary>
        internal static string Day17Jets {
            get {
                return ResourceManager.GetString("Day17Jets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10,17,7
        ///8,14,15
        ///15,5,5
        ///17,7,13
        ///6,6,15
        ///9,1,11
        ///15,11,16
        ///11,5,3
        ///1,9,9
        ///8,1,9
        ///17,6,11
        ///13,3,12
        ///8,17,11
        ///3,7,12
        ///4,12,9
        ///4,13,11
        ///8,9,3
        ///7,13,15
        ///9,16,14
        ///16,6,12
        ///6,16,7
        ///17,11,7
        ///5,15,11
        ///5,4,13
        ///13,9,2
        ///16,12,11
        ///6,14,10
        ///2,8,13
        ///12,11,4
        ///9,1,10
        ///3,8,9
        ///3,14,13
        ///7,15,5
        ///6,10,16
        ///8,13,17
        ///10,17,8
        ///8,4,11
        ///5,14,9
        ///11,9,3
        ///2,7,10
        ///14,9,5
        ///6,6,14
        ///14,7,16
        ///15,3,7
        ///11,11,17
        ///16,12,14
        ///9,12,4
        ///3,16,10
        ///6,4,10
        ///4,4,15
        ///5,3,11
        ///6,15,6
        ///10,16,5
        ///10,11,1
        ///16,6,13
        ///14,3,11
        ///10,12,2
        ///14,14,10
        ///12,16,7
        ///15,14,13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day18Lava {
            get {
                return ResourceManager.GetString("Day18Lava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint 1: Each ore robot costs 4 ore. Each clay robot costs 4 ore. Each obsidian robot costs 4 ore and 17 clay. Each geode robot costs 4 ore and 20 obsidian.
        ///Blueprint 2: Each ore robot costs 3 ore. Each clay robot costs 3 ore. Each obsidian robot costs 2 ore and 12 clay. Each geode robot costs 2 ore and 10 obsidian.
        ///Blueprint 3: Each ore robot costs 3 ore. Each clay robot costs 3 ore. Each obsidian robot costs 2 ore and 20 clay. Each geode robot costs 3 ore and 18 obsidian.
        ///Blueprint 4: Each ore robo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day19Robots {
            get {
                return ResourceManager.GetString("Day19Robots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3948
        ///8349
        ///-4882
        ///-1065
        ///9657
        ///-7890
        ///2902
        ///4136
        ///369
        ///-2026
        ///7899
        ///6971
        ///8465
        ///-3249
        ///1569
        ///158
        ///-7433
        ///1502
        ///-8019
        ///5490
        ///-9467
        ///8375
        ///5796
        ///-2925
        ///-5870
        ///917
        ///-67
        ///9033
        ///-2897
        ///-1464
        ///4789
        ///-7483
        ///-5
        ///8954
        ///1296
        ///-9920
        ///-5776
        ///7037
        ///-5211
        ///-5785
        ///179
        ///-4519
        ///340
        ///-139
        ///9417
        ///9013
        ///6984
        ///-6111
        ///-4459
        ///6347
        ///5516
        ///-558
        ///-7963
        ///-1988
        ///-3518
        ///8174
        ///-1819
        ///-3340
        ///8771
        ///429
        ///-9583
        ///-7735
        ///-121
        ///-2672
        ///4127
        ///-2566
        ///8332
        ///-2793
        ///195
        ///5344
        ///-106
        ///-847
        ///-1564
        ///8469
        ///-6412
        ///-7046
        ///5567
        ///-9020
        ///1994
        ///4743
        ///1867
        ///-3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day20Mixing {
            get {
                return ResourceManager.GetString("Day20Mixing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cjdb: 3
        ///hhfs: 5
        ///jvjn: 4
        ///tjzm: bngm * mrfm
        ///mbbs: 2
        ///dzlq: tcdz * bjdj
        ///htzp: 3
        ///hsmn: 5
        ///sblh: 2
        ///pghw: 5
        ///pqtp: vtcr * bcts
        ///mvgz: 2
        ///sszn: 3
        ///zqlr: nlfq * htfq
        ///djsb: 2
        ///vccw: zzsz * thbz
        ///tlvg: fncr + glvj
        ///grql: nqch * jhmw
        ///rngv: 4
        ///prjv: 2
        ///rmdl: lzdr * qpzh
        ///pdqm: 2
        ///jrpn: zcnv + pgqr
        ///llzf: 2
        ///bzfp: qbwz + zsts
        ///bvsf: rbcd + npcs
        ///jmpm: 3
        ///zgrs: 15
        ///lcrs: 5
        ///cqcc: swtj + wnzt
        ///vhts: 2
        ///pbgz: 1
        ///mqpb: 2
        ///jzcf: 2
        ///sfls: 10
        ///cnhh: 8
        ///clsh: mcwb * jfrq
        ///cqch: 4
        ///brvd: 19
        ///fprh: 2
        ///dccm: gbhn / tczb
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day21Monkey {
            get {
                return ResourceManager.GetString("Day21Monkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                   ............#..#..................#............#.......#..............#.............................
        ///                                                  ...#...#...#.......#............................#.#.....#..#...........................#......#.....
        ///                                                  #.....#....#....#...............#..#.........#..................#......................#.##......#..
        ///                                                  ...#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day22Password {
            get {
                return ResourceManager.GetString("Day22Password", resourceCulture);
            }
        }
    }
}
