//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4601
        ///1583
        ///2995
        ///5319
        ///3352
        ///1722
        ///4331
        ///5840
        ///3339
        ///5341
        ///3415
        ///1297
        ///1610
        ///2703
        ///
        ///5928
        ///1266
        ///6405
        ///4354
        ///2815
        ///1621
        ///3545
        ///1733
        ///2162
        ///1155
        ///3674
        ///4055
        ///4262
        ///2115
        ///
        ///25873
        ///16103
        ///17042
        ///
        ///6479
        ///1521
        ///6902
        ///6331
        ///6146
        ///1591
        ///2063
        ///2149
        ///1463
        ///1865
        ///2598
        ///6893
        ///3617
        ///
        ///1431
        ///8935
        ///8134
        ///8885
        ///8698
        ///8884
        ///7982
        ///3617
        ///7079
        ///
        ///34031
        ///8383
        ///
        ///3697
        ///1199
        ///3703
        ///1322
        ///5679
        ///1627
        ///5910
        ///1092
        ///6445
        ///2371
        ///3672
        ///2281
        ///2710
        ///5111
        ///
        ///17480
        ///
        ///58355
        ///
        ///3711
        ///2406
        ///2101
        ///1406
        ///5376
        ///2149
        ///4608
        ///6768
        ///6322
        ///3792
        ///42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Elves {
            get {
                return ResourceManager.GetString("Day01Elves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day02Rock {
            get {
                return ResourceManager.GetString("Day02Rock", resourceCulture);
            }
        }
    }
}
