//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.InputData", typeof(InputData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4601
        ///1583
        ///2995
        ///5319
        ///3352
        ///1722
        ///4331
        ///5840
        ///3339
        ///5341
        ///3415
        ///1297
        ///1610
        ///2703
        ///
        ///5928
        ///1266
        ///6405
        ///4354
        ///2815
        ///1621
        ///3545
        ///1733
        ///2162
        ///1155
        ///3674
        ///4055
        ///4262
        ///2115
        ///
        ///25873
        ///16103
        ///17042
        ///
        ///6479
        ///1521
        ///6902
        ///6331
        ///6146
        ///1591
        ///2063
        ///2149
        ///1463
        ///1865
        ///2598
        ///6893
        ///3617
        ///
        ///1431
        ///8935
        ///8134
        ///8885
        ///8698
        ///8884
        ///7982
        ///3617
        ///7079
        ///
        ///34031
        ///8383
        ///
        ///3697
        ///1199
        ///3703
        ///1322
        ///5679
        ///1627
        ///5910
        ///1092
        ///6445
        ///2371
        ///3672
        ///2281
        ///2710
        ///5111
        ///
        ///17480
        ///
        ///58355
        ///
        ///3711
        ///2406
        ///2101
        ///1406
        ///5376
        ///2149
        ///4608
        ///6768
        ///6322
        ///3792
        ///42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Elves {
            get {
                return ResourceManager.GetString("Day01Elves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Z
        ///C Z
        ///A X
        ///A X
        ///B Z
        ///B Z
        ///B Z
        ///A Z
        ///B X
        ///A X
        ///A X
        ///A X
        ///C Z
        ///C Z
        ///C X
        ///A X
        ///A X
        ///A X
        ///C Z
        ///B Z
        ///C Z
        ///A Y
        ///B Z
        ///A X
        ///C Y
        ///A X
        ///A X
        ///C Y
        ///C Z
        ///A Y
        ///B Z
        ///A X
        ///C Y
        ///B Z
        ///B Z
        ///B Z
        ///A X
        ///C X
        ///C X
        ///B Z
        ///A X
        ///C Z
        ///A X
        ///B Z
        ///A Y
        ///C X
        ///A X
        ///C Z
        ///C Z
        ///B Z
        ///C Y
        ///C X
        ///C X
        ///C X
        ///C X
        ///A Y
        ///C Y
        ///C Z
        ///C Y
        ///A X
        ///C Y
        ///A X
        ///B Z
        ///A Y
        ///C X
        ///A X
        ///B Y
        ///A X
        ///C X
        ///C X
        ///C Z
        ///A X
        ///C X
        ///A X
        ///C X
        ///B Z
        ///A Z
        ///B Y
        ///B Z
        ///B Z
        ///A X
        ///C Y
        ///B X
        ///A X
        ///A X
        ///B Z
        ///A X
        ///C X
        ///C Z
        ///C Z
        ///A X
        ///C Z
        ///C Z
        ///C Z
        ///C X
        ///C Z
        ///A X
        ///B Z
        ///B Y
        ///C Z
        ///B Z
        ///B Z
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Rock {
            get {
                return ResourceManager.GetString("Day02Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gfWpjRRQffQGCHHJsGqjsj
        ///SclzJZZvmmnPbJtVSqqNBqVCBdSCsd
        ///tlbvZJDZtmtPcJmlPnhMFQWWpMRFTfLDRRTWRp
        ///HjMPgSWjVrjgbHRRSSMRgjRdpdbGdlcdCvQfcCdlwQJfdf
        ///LNDnhtNtLNFFZDtFnhzvdldDflvvDCdlJfldpJ
        ///ZFLFZZmFtFtTNTSPRrVPWWMpRP
        ///qLBSBLRwmgzqCbzCffDlrfCV
        ///TFFFHNWFMFFMpHpGHMTHGNhrldWZCsdZsslZlZfrflDVss
        ///PTMcPGntTThHhTGctnMvSwjjvmmqLBmnjqqgCR
        ///nClJtMwwntqVVPJcgZqq
        ///mjpsDcrcSSFFPZqFBWWgVP
        ///vQcjsvhrvvrmhbmNHMNnlHbNMtCtNM
        ///bgvvhnTQtjrrrhsDDf
        ///pLSMltLzLLSjFrSSjrSJHD
        ///zNWRLBdZPllPQtCvttgCqb
        ///DRlDrrFTNDNlgzsGTBfcnqhhcnJfcrCSqc
        ///MMmm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Rucksack {
            get {
                return ResourceManager.GetString("Day03Rucksack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22-77,14-96
        ///7-99,65-98
        ///22-36,37-62
        ///25-94,24-67
        ///6-91,1-6
        ///88-88,2-88
        ///27-89,58-96
        ///21-82,9-94
        ///38-79,27-80
        ///4-90,30-55
        ///84-97,52-93
        ///12-59,11-12
        ///4-14,5-12
        ///50-84,49-89
        ///3-98,1-3
        ///91-95,8-22
        ///15-66,17-67
        ///27-27,27-90
        ///36-37,37-96
        ///31-32,32-80
        ///1-79,2-78
        ///36-85,20-36
        ///2-2,2-98
        ///33-81,80-99
        ///4-73,45-72
        ///3-89,1-4
        ///6-92,21-91
        ///7-93,2-92
        ///47-89,47-50
        ///64-84,63-65
        ///22-85,21-91
        ///16-31,11-14
        ///4-93,3-93
        ///15-61,61-62
        ///21-23,22-88
        ///59-59,11-58
        ///23-23,22-89
        ///19-87,78-86
        ///13-82,19-83
        ///22-88,76-92
        ///46-47,46-46
        ///30-31, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Assignment {
            get {
                return ResourceManager.GetString("Day04Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             [M] [S] [S]            
        ///        [M] [N] [L] [T] [Q]        
        ///[G]     [P] [C] [F] [G] [T]        
        ///[B]     [J] [D] [P] [V] [F] [F]    
        ///[D]     [D] [G] [C] [Z] [H] [B] [G]
        ///[C] [G] [Q] [L] [N] [D] [M] [D] [Q]
        ///[P] [V] [S] [S] [B] [B] [Z] [M] [C]
        ///[R] [H] [N] [P] [J] [Q] [B] [C] [F]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 1 from 7 to 4
        ///move 3 from 4 to 7
        ///move 4 from 3 to 4
        ///move 5 from 6 to 9
        ///move 1 from 8 to 1
        ///move 2 from 3 to 2
        ///move 3 from 4 to 6
        ///move 1 from 3 to 6
        ///move 9 from 7 to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05Crates {
            get {
                return ResourceManager.GetString("Day05Crates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zdrrgvvntvtzzssgcgqqbvqqzmqmrrprjjpmpwpvpqpwppfqqnvvjbjcbbrnnvwnvnqnncvvqnvqvmmdzdrzzjmmfzmztzczzjpjllgzgnzgznzpzhhvppmjjtbjbjgbjjpfphfhthpprbbzzhbzzvjjsttjwtjwjllzplzlhlqlfqfvflfvlvqvqsshccgffvzzqllpjllcqcpqcpqccbgcccvwvlldclcppcggjhhtbhbrbwbllldndhnnmnmcccvfvtftrfttlhttgltlflgflfrrftrtrgrmggbccnvccvssbmsmnsmszmmsbshbhpbhhtccnmngmnnntznttwnnmffdccrhrshhzhszslzlqqqsqhhrrvmrrhrmhrrdppshpssjhhhtzhzpzzzbrrqqhhtltgltgghlhpphmmbllczcgcrgcrcmmdjdvdssdbsshqqrprhrfrqrlldggpglplqlgqqvfqqwhqqclcwwbrbwbzzmcczqqpzpzhpz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06Tuning {
            get {
                return ResourceManager.GetString("Day06Tuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir jmtrrrp
        ///dir jssnn
        ///dir lbrmb
        ///11968 pcccp
        ///$ cd jmtrrrp
        ///$ ls
        ///77968 chq.jvb
        ///dir fmgsql
        ///$ cd fmgsql
        ///$ ls
        ///dir dbnsfp
        ///dir vvp
        ///$ cd dbnsfp
        ///$ ls
        ///51021 crlq.lrj
        ///186829 dhcrzvbr.wmn
        ///16232 fvhn.fqm
        ///54150 qpbqqj.rpg
        ///$ cd ..
        ///$ cd vvp
        ///$ ls
        ///179105 rrcsndz.tzp
        ///$ cd ..
        ///$ cd ..
        ///$ cd ..
        ///$ cd jssnn
        ///$ ls
        ///dir bphfqs
        ///dir dbnsfp
        ///dir pcccp
        ///dir snr
        ///dir zjbvwsnv
        ///$ cd bphfqs
        ///$ ls
        ///110077 dhcrzvbr.wmn
        ///$ cd ..
        ///$ cd dbnsfp
        ///$ ls
        ///dir hgvh
        ///dir jtqdcmsz
        ///154197 rrcsndz.tzp
        ///$ cd hgvh
        ///$  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07Terminal {
            get {
                return ResourceManager.GetString("Day07Terminal", resourceCulture);
            }
        }
    }
}
